// The Motivation tab's quote pool. Voice: sharp older sibling or favorite
// teacher texting you, not a greeting card. Concrete, specific, a little
// witty — grounded in an actual student moment, not abstract cheerleading.
//
// Editing this file: just add or remove strings from QUOTES below. No other
// code needs to change — Motivation.jsx picks a random one (never the same
// one twice in a row) every time the tab loads.
export const QUOTES = [
  "Your GPA doesn't know you almost didn't submit that essay at 11:58pm. It just knows you did. That's the whole game, showing up messy beats not showing up at all.",
  "You've read the same paragraph four times and it still hasn't landed. That's not stupidity, that's a brain asking for a five minute walk. Go take it.",
  "Nobody in that group chat posting their acceptance letters is showing you the eleven rejections first. Comparing your rough draft to their highlight reel is a rigged game.",
  "The all nighter isn't a personality trait, it's a scheduling problem wearing a cape. Pick one class this week and start the assignment two days early, just to see.",
  "Failing that one quiz doesn't put a dent in who you are. It puts a dent in one quiz. Keep the two separate and you'll survive the semester fine.",
  "You don't need a whole new system, seventeen apps, and a color coded planner. You need to open the laptop and do the ugly first draft. That's it.",
  "Scrolling at 2am isn't rest, it's just tired procrastination with better lighting. Put the phone on the other side of the room tonight and see what happens.",
  "Asking the \"dumb\" question in office hours is cheaper than guessing wrong on the exam. Your professor has heard worse. Go email them.",
  "The classmate who looks like they're not trying is also stressed about something you can't see. Nobody's doing this effortlessly, they're just better at hiding the mess.",
  "You don't have to feel motivated to start. You have to start, and then sometimes the motivation shows up late, out of breath, apologizing.",
  "That blank document has been open for forty minutes and you've typed a title and deleted it three times. Write one bad sentence. You can fix bad. You can't fix blank.",
  "Burnout doesn't announce itself, it just makes everything feel thirty percent harder than it should. If studying suddenly feels impossible, the fix might be sleep, not more effort.",
  "One bad midterm is data, not a verdict. Use it to figure out what actually went wrong instead of using it to decide you're bad at the subject.",
  "You are allowed to close the seventeen tabs and the three group chats and just read the one chapter. Multitasking is mostly just doing five things badly at once.",
  "Nobody remembers the semester you had a rough week. They remember whether you finished the degree. Zoom out before you spiral over one bad Tuesday.",
  "The freeloader in your group project isn't a reflection of your work ethic. Document what you did, flag it calmly, and stop carrying guilt that isn't yours.",
  "Rewriting the same paragraph for the ninth time isn't perfectionism, it's fear wearing a nice outfit. Ship the decent version, you can always fix version two.",
  "Your professor forgot your name and it wrecked your whole afternoon. They also forget where they left their coffee. It wasn't about you.",
  "The printer breaking an hour before your deadline is not a sign from the universe. It's a printer. Email the PDF and keep moving.",
  "You skipped one class and now you're spiraling about dropping out. That's the anxiety talking louder than the facts. Go to the next one, that's the whole fix.",
  "Cramming works about as well as tape on a broken chair leg, it looks handled for a second. Forty minutes a day for a week beats one twelve hour panic session.",
  "The gap between your plan and your actual Tuesday is normal. Nobody's week one syllabus survives contact with real life. Adjust the plan, don't abandon it.",
  "You don't owe anyone a productive weekend. Rest isn't something you earn after the to do list hits zero, it's something you need before you hit zero yourself.",
  "Imposter syndrome doesn't mean you don't belong here. It usually means you're finally around people as capable as you, and it's rattling. Stay anyway.",
  "The library at midnight full of stressed strangers is oddly the least lonely place on campus. Everyone in that room is also behind on something. You're in good company.",
  "You don't need to feel ready to email the professor about the extension. You need to send the email while it's still true that you're trying.",
  "Six unread messages from your group project chat and a pit in your stomach isn't a character flaw, it's a Tuesday. Answer the easiest one first, the rest gets easier.",
  "The version of you from a month ago would be relieved to know you're still here, tired but still turning things in. That counts for more than it feels like.",
  "Highlighting the textbook feels like studying. It's mostly just coloring with extra steps. Close the book and try explaining the chapter out loud instead.",
  "You compared your first draft to someone else's final draft again. Different stages, not different talent. Let yourself be bad at the beginning like everyone else was.",
  "Snoozing the 7am alarm four times doesn't make you lazy, it makes you human with a bad sleep schedule. Fix the 11pm scroll before you blame the 7am alarm.",
  "The panic in the ten seconds after you hit submit is not useful information about your grade. It's just your nervous system being dramatic. Breathe, it already sent.",
  "You don't have to love the subject to pass the subject. Some classes you survive, not savor. Get through it, then go take the one you actually care about.",
  "Nobody's GPA has ever gone up because they stayed up worrying about it at 1am instead of sleeping. Worry burns energy, not points. Go to bed.",
  "The Sunday night dread before a hard week is usually worse than the week turns out to be. Your brain likes to preview the scary trailer before the actual movie.",
  "You don't need to answer every notification the second it arrives. The group chat will survive twenty unread minutes while you finish one paragraph.",
  "The two hours you spent reorganizing your notes app instead of studying felt productive. It wasn't. Open the actual notes, the app can wait.",
  "Getting a B on something you worked hard for still counts as working hard. The grade doesn't erase the effort, it just doesn't always match it.",
  "You keep waiting to feel like you deserve the good grade before you'll believe it's real. You don't have to feel worthy of it, you just had to have earned it, and you did.",
  "The friend who seems to have it all figured out was also stressed about something last week. You're just not in that group chat. Stop comparing your inside to their outside.",
  "One missed assignment doesn't cancel out a whole semester of showing up. Email your professor, take the hit if there is one, and keep going to the next class.",
  "You don't have to finish the whole outline tonight. You have to open the document and write one real sentence. Momentum starts smaller than people admit.",
  "The exam room goes quiet and your brain goes blank for the first ninety seconds, every single time. That's not proof you didn't study, that's just what nerves do. Keep writing.",
  "Waiting for motivation before you start the assignment is like waiting for the bus to come find you at home. Walk to the stop, start the doc.",
  "You're not behind everyone else, you're on a slightly different clock than the loudest people in the room. Quiet progress still counts as progress.",
  "The urge to check your grade the second it posts and then spiral for twenty minutes either way isn't helping. Check it, feel the feeling, then close the tab and move on.",
  "Forgetting to eat because you were \"in the zone\" studying isn't dedication, it's a warning sign your zone needs a snack break built into it.",
  "You don't need to be a different person to get through finals. You need a decent sleep schedule, one to do list, and permission to stop at some point each night.",
  "The assignment felt impossible at 4pm and somehow got done by midnight. Your past self keeps bailing your present self out. Try trusting that pattern a little sooner next time.",
];
